const weatherTranslations = {
  // Daftar terjemahan cuaca
  Clear: "Cerah",
  Sunny: "Cerah",
  "Partly cloudy": "Berawan sebagian",
  Cloudy: "Berawan",
  Overcast: "Mendung",
  Mist: "Kabut",
  "Patchy rain possible": "Hujan ringan kemungkinan terjadi",
  "Patchy snow possible": "Salju ringan kemungkinan terjadi",
  "Patchy sleet possible": "Hujan es ringan kemungkinan terjadi",
  "Patchy freezing drizzle possible": "Gerimis beku ringan kemungkinan terjadi",
  "Thundery outbreaks possible": "Potensi petir",
  "Blowing snow": "Salju berserakan",
  Blizzard: "Badai salju",
  Fog: "Kabut",
  "Freezing fog": "Kabut beku",
  "Patchy light drizzle": "Gerimis ringan",
  "Light drizzle": "Gerimis ringan",
  "Freezing drizzle": "Gerimis beku",
  "Heavy freezing drizzle": "Gerimis beku yang intens",
  "Patchy light rain": "Hujan ringan",
  "Light rain": "Hujan ringan",
  "Moderate rain at times": "Hujan sedang kadang-kadang",
  "Moderate rain": "Hujan sedang",
  "Heavy rain at times": "Hujan deras kadang-kadang",
  "Heavy rain": "Hujan deras",
  "Light freezing rain": "Hujan beku ringan",
  "Moderate or heavy freezing rain": "Hujan beku sedang atau intens",
  "Light sleet": "Hujan es ringan",
  "Moderate or heavy sleet": "Hujan es sedang atau intens",
  "Patchy light snow": "Salju ringan",
  "Light snow": "Salju ringan",
  "Patchy moderate snow": "Salju sedang",
  "Moderate snow": "Salju sedang",
  "Patchy heavy snow": "Salju intens",
  "Heavy snow": "Salju intens",
  "Ice pellets": "Bijian es",
  "Light rain shower": "Hujan ringan",
  "Moderate or heavy rain shower": "Hujan sedang atau deras",
  "Torrential rain shower": "Hujan lebat",
  "Light sleet showers": "Hujan es ringan",
  "Moderate or heavy sleet showers": "Hujan es sedang atau deras",
  "Light snow showers": "Hujan salju ringan",
  "Moderate or heavy snow showers": "Hujan salju sedang atau deras",
  "Light showers of ice pellets": "Hujan bijian es ringan",
  "Moderate or heavy showers of ice pellets":
    "Hujan bijian es sedang atau deras",
  "Patchy light rain with thunder": "Hujan ringan dengan petir",
  "Moderate or heavy rain with thunder": "Hujan sedang atau deras dengan petir",
  "Patchy light snow with thunder": "Salju ringan dengan petir",
  "Moderate or heavy snow with thunder": "Salju sedang atau deras dengan petir",
};

export default weatherTranslations;
